version: '3.9'

services:
  app:
    build:
      target: "development"
    volumes:
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - .:/geocms
      - uploads:/app/public/uploads

  cron:
    build:
      target: "development"
    volumes:
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - .:/geocms

  sidekiq:
    build:
      target: "development"
    volumes:
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - .:/geocms
      - uploads:/app/public/uploads

volumes:
  postgres:
  redis:
  rails_cache:
  bundle:
  uploads:
